[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "always"

[[services]]
name = "google-maps-scraper"

[services.variables]
PORT = "8080"
HEADLESS = "true"
TIMEOUT = "300"
MAX_DEPTH = "5"
WORKERS = "1"
