[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 900
restartPolicyType = "always"

[[services]]
name = "google-maps-scraper"

[services.variables]
PORT = "8080"
HEADLESS = "true"
TIMEOUT = "600"
MAX_DEPTH = "3"
WORKERS = "1"
MEMORY_LIMIT = "4096"
PLAYWRIGHT_BROWSERS_PATH = "/opt/browsers"
RAILWAY_RUN_UID = "1001"
